import React from "react";
import icon1 from "../assets/icon1.png";
import icon2 from "../assets/icon2.png";
import icon3 from "../assets/icon3.png";

function Hero2() {
  return (
    <>
      <div className="flex mt-10 justify-evenly bg-blue-100 py-10 w-full">
        <div className="flex flex-col items-center">
          <div>
            <img src={icon1} alt="" />
          </div>
          <div>
            <p className="text-black mt-5 font-semibold mb-3">Search</p>
          </div>
          <div className="text-center text-[#4D4D4D] text-sm">
            <p> Simply add a keyword or a term related to</p>
            <p> your business in the slogan maker search</p>
            <p> box. Wait for the magic to happen.</p>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <div>
            <img src={icon2} alt="" />
          </div>
          <div>
            <p className="text-black mt-5 font-semibold mb-3">Select</p>
          </div>
          <div className="text-center text-[#4D4D4D] text-sm">
            <p>Choose from thousands of options</p>
            <p> generated by the slogan maker that fit your </p>
            <p> needs.</p>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <div>
            <img src={icon3} alt="" />
          </div>
          <div>
            <p className="text-black mt-5 font-semibold mb-3">Stand out</p>
          </div>
          <div className="text-center text-[#4D4D4D] text-sm">
            <p> Congrats on your new slogan. It's time to win </p>
            <p> the world!</p>
          </div>
        </div>
      </div>
    </>
  );
}

export default Hero2;
